name: Deploy App

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: hey
        run: echo "Deploying to PRODUCTION!"
